name: TSC Meeting agenda item
description: Propose an agenda item to discuss at an upcoming TSC meeting
title: "AGENDA TOPIC"
labels: ["tsc-meeting"]
assignees: 
  - erikreppel-cb
  - Naomi-Wash
body:
  - type: markdown
    attributes:
      value: |
        The TSC is always looking for topics of interest to the community. 
        Please set the issue title above to your proposed agenda topic and fill out
        the details below to have it added to a future TSC meeting agenda.
        Please note that you must be available to lead this discussion at a TSC meeting.
        You can find information about TSC meetings and how to join them in the
        [TSC README](https://github.com/x402-foundation/tsc/blob/main/README.md).
  - type: textarea
    id: details
    attributes:
      label: Please share any additional details on this topic
    validations:
      required: true
  - type: textarea
    id: tac-action
    attributes:
      label: Detail what actions or feedback you would like from the TSC
    validations:
      required: true
  - type: dropdown
    id: topic-length
    attributes:
      label: How much time do you need for this topic?
      description: Pick the option closest to the time you need for the topic.
      multiple: false
      options:
        - 5 minutes or less
        - 10 - 20 minutes
        - At least 30 minutes
